### ISSUE TITLE
ConfigMap "bevel-vault-script" not found when running Besu genesis chart for no-vault no-proxy

### ISSUE THREAD

**Issue by alvaropicazo** [hyperledger-bevel/bevel#2638]
**Describe the bug**
The  besu genesis init job from the besu genesis chart is not completing.

**To Reproduce**
1. Run Besu genesis chart, following the no-vault and no-proxy approach.
2. Describe the pod so you will see the following error:

**Expected behavior**
The job should complete.

**Screenshots**
![Screenshot 2024-12-10 at 09 15 57](https://github.com/user-attachments/assets/2f2b41ee-7d8e-4873-9674-76eadd70fdba)

**Comment by sownak** [comment]
Fixed with #2639
